services:
  user-api:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: user-api
    image: user-api
    volumes:
      - ./app:/app/app
    ports:
      - "8001:8000"
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    depends_on:
      - user-db
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8000/user/health || exit 1" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  user-db:
    image: postgres:17-alpine
    container_name: user-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data
      # - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: sabuhi@mail.com
      PGADMIN_DEFAULT_PASSWORD: sabuhi123
    container_name: pgadmin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  user-db-data:
    name: user-db-data
  pgadmin_data:
    name: pgadmin_data