# syntax=docker/dockerfile:1

FROM python:3.13-slim-bookworm AS build

ENV POETRY_VERSION=2.2.1 \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"

ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN pip install "poetry==$POETRY_VERSION"

WORKDIR $PYSETUP_PATH

COPY poetry.lock pyproject.toml ./

RUN --mount=type=cache,target=/root/.cache/pypoetry \
    poetry install --no-root

COPY alembic ./alembic
COPY alembic.ini ./alembic.ini
COPY app ./app
COPY entrypoint.sh ./entrypoint.sh

FROM python:3.13-slim-bookworm AS runtime

ENV VENV_PATH="/opt/pysetup/.venv" \
    PATH="/opt/pysetup/.venv/bin:$PATH"

RUN groupadd -g 1001 appgroup && \
    useradd -u 1001 -g appgroup -m -d /home/appuser -s /bin/bash appuser

WORKDIR /app

# COPY --from=build --chown=appuser:appgroup /opt/pysetup/.venv /opt/pysetup/.venv
# COPY --from=build --chown=appuser:appgroup /opt/pysetup/ ./

COPY --from=build --chown=appuser:appgroup $VENV_PATH $VENV_PATH
COPY --from=build --chown=appuser:appgroup /opt/pysetup/app ./app
COPY --from=build --chown=appuser:appgroup /opt/pysetup/alembic ./alembic
COPY --from=build --chown=appuser:appgroup /opt/pysetup/alembic.ini ./alembic.ini
COPY --from=build --chown=appuser:appgroup /opt/pysetup/entrypoint.sh ./entrypoint.sh

USER appuser

ENTRYPOINT ["./entrypoint.sh"]
CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]