# FOR ADDING DEPENDENCY TO POETRY
# docker compose -f docker-compose.poetry-alembic.yml run --rm test poetry add <package_name>
#
# FOR RUNNING MIGRATIONS
# docker compose -f docker-compose.poetry-alembic.yml run --rm auth-p poetry run alembic upgrade head
#
# FOR CREATING NEW MIGRATIONS
# docker compose -f docker-compose.poetry-alembic.yml run --rm test poetry run alembic revision --autogenerate -m "Initial migration"
# alembic init alembic
# docker compose -f docker-compose.poetry-alembic.yml run --rm test poetry run alembic init alembic

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.poetry-alembic
    container_name: poetry
    volumes:
      - .:/app
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@test-db:5432/test_db
    depends_on:
      - test-db

  test-db:
    image: postgres:17-alpine
    container_name: test-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - test-db-data:/var/lib/postgresql/data
      # - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  test-db-data:
  